### ISSUE TITLE
Cannot override pom.xml properties for TeamCity CI/CD

### ISSUE THREAD

**Issue by ahahn95** [adobe/aem-project-archetype#197]
### Expected Behaviour
I should be able to pass in environment variables that will override the defined variables so my build will deploy to a hosted AEM instance and not just die on the TeamCity agent/instance.

The variables should show up as
<aem.host>[MY-AWS-IP-ADDRESS]</aem.host>
<aem.port>4502</aem.port>
...

### Actual Behaviour

The variables actually show up as

<aem.host>localhost</aem.host>
<aem.port>4502</aem.port>
...

#### Steps to Reproduce

My build step in TeamCity is `clean install` with the following env vars

-Daem.host=%env.host% -Daem.port=%env.port% -Daem.sling.user=%env.sling_user% -Daem.sling.password=%env.sling_password% -Daem.vault.user=%env.vault_user% -Daem.vault.password=%env.vault_password%

#### Platform and Version

AEM 6.3

#### Sample Code that illustrates the problem

The important parts from the TeamCity build command is

/usr/lib/jvm/java-8-oracle/bin/java -classpath /home/buildagent/buildAgent/tools/maven3_3/boot/plexus-classworlds-2.5.2.jar: org.codehaus.plexus.classworlds.launcher.Launcher -f /home/buildagent/buildAgent/work/a7888acb4e4dc437/pom.xml -B clean install -Daem.host=[MY-AWS-IP-ADDRESS] -Daem.port=4502 -Daem.sling.user=admin -Daem.sling.password=admin -Daem.vault.user=admin -Daem.vault.password=admin

**Comment by bpauli** [comment]
Hi @ahahn95, to auto deploy the generate project you have to activate the profile `autoInstallPackage` . Please have a look to the README.md how this can be done. All properties you can override with the cli can be found at [1]. For example instead of `aem.sling.password` you have to use `sling.password`.

HTH
Burkhard

[1] https://github.com/adobe/aem-project-archetype/blob/master/src/main/archetype/pom.xml#L36-L44
