### ISSUE TITLE
Split components into /content and /structure

### ISSUE THREAD

**Issue by pdmyrs** [adobe/aem-project-archetype#328]
### Expected Behaviour

Previous versions of the Archetype generated frontend components into two separate folders - one for draggable content components and one for structure components.

Example from wknd created with archetype 22:

ui.apps/src/main/content/jcr_root/apps/wknd/components/content
ui.apps/src/main/content/jcr_root/apps/wknd/components/structure

### Actual Behaviour

Now all components are placed in the ui.apps/src/main/content/jcr_root/apps/wknd/components folder.

IMO is useful to organize components into content and structure.
Was the change in Archetype 23 intentional or is it a bug?

If it is intentional please explain the rational for the change.

#### Platform and Version

6.5.3

#### Sample Code that illustrates the problem

Example from wknd created with archetype 22:

ui.apps/src/main/content/jcr_root/apps/wknd/components/content
ui.apps/src/main/content/jcr_root/apps/wknd/components/structure

#### Logs taken while reproducing problem

**Comment by gabrielwalt** [comment]
Hi @pdmyrs,

The way the proxy components are grouped into folders has no impact whatsoever, and you can modify it to what your development team prefers. What is relevant is that you assign the components to different groups that correspond to where you want authors to use them, typically: "Structure," "Content," and "Form."

I decided to remove the intermediate folders to simplify things a little bit because I see no reason why we'd have the Core Components grouped one way, but the proxy components grouped another way. Having both folders organized identically should simplify it a bit.

I'd also argue that it makes it easier to change the context in which a component is allowed if you don't let the context influence its path. For example, in the previous folder structure, the `languagenavigation` component was mistakenly placed into the `content` folder. Fixing this would have required the content to be refactored as you'd also want to move the component's folder unless you agree that these folders don't mean much.

Now you could argue that we then should also get rid of the `form` folder. I'd agree, especially since there's another issue with the `form` folder: the `form/container` component must belong to the "Content" component group or authors couldn't place it into the regular page content. But if we move the form components out of their folder, we'd then need to prefix them to something like `formcontainer`, `formbutton`, `formtext`, and so on, which would deviate again from the Core Component folders which we cannot modify… But as my position is that these folders don't have much meaning, I prefer to go with keeping them aligned with the Core Components.

But your experience in projects maybe shows differently to what I'm assuming. I'm open to hearing more in detail why you think that these folders were helpful.

**Comment by pdmyrs** [comment]
Hi @gabrielwalt 

I  like having two distinct folders purely for organizational purposes. We not only put the proxy components in the "content" folder, but also our custom "content" components. Likewise we put our custom "structure" components in the "structure" folder. ( We don't use form components at all). A single folder starts to get filled up and it is less apparent which components are content vs structure when a developer looks at  the project structure. That's the only reason.

**Comment by gabrielwalt** [comment]
It's true that since you'll add further proxy components to the list, you'll end up not having the same structure there than the Core Components have, and a more structured approach indeed makes sense.

However, how you structure that folder is very opinionated, so, at least for now, I'd still go with a more neutral structure out-of-the-box, but you're free to organize them the way you prefer.

If others also have a preference for reverting the `content` and `structure` folder, I'm open to reconsidering this decision. Closing this issue for the time being.

**Comment by vaneeghemk** [comment]
Hi @gabrielwalt.

While I totally get wanting to have a unified approach in core components and the archetype, one could also argue that core components is not as much of an actual AEM project, as a framework. As such, the structure there doesn't matter as much, as you leave the usage of the components up to the implementor. 
However, by updating the archetype, you're taking away a valuable structural decision that should be made on a project level - as you pointed out both are valid. Rather than fixing the archetype on one decision (allowing no flexibility), could we not make this a configuration during the setup, so this decision can be made on a case-per-case basis?

Open to hearing your opinion on this & thanks in advance,
Koen
