### ISSUE TITLE
Archetype 23 is failing for angular at npm test

### ISSUE THREAD

**Issue by amit-gup** [adobe/aem-project-archetype#484]
### Expected Behaviour
   Project Should be Build after creation from the archetype

### Actual Behaviour
  Breaking  build at ui.frontend Module

#### Steps to Reproduce
  create an angular project from 23 archetype. Sample code is given below

#### Platform and Version
          Windows & Ubuntu 16 both

#### Sample Code that illustrates the problem

mvn org.apache.maven.plugins:maven-archetype-plugin:3.2.0:generate -B -DarchetypeGroupId=com.adobe.granite.archetypes -DarchetypeArtifactId=aem-project-archetype -DarchetypeVersion=23 -DfrontendModule=angular -DgroupId="DummyProject" -Dversion=1.0-SNAPSHOT -Dpackage="com.DummyProject" -DappId="DummyProject" -DartifactId="DummyProject" -DappTitle="DummyProject" -DincludeDispatcherConfig=n -DincludeErrorHandler=n -DincludeExamples=y

#### Logs taken while reproducing problem

![Archetype23](https://user-images.githubusercontent.com/25603683/91732644-1fee8a00-ebc6-11ea-988a-708a8cf9578a.PNG)

**Comment by viveksr2** [comment]
The error is actually appearing while running 'mvn -PautoInstallSinglePackage clean install', instead of 'mvn archetype:generate'

**Comment by blackbyte-pl** [comment]
Hello @amit-gup,
This issue is a result of updating some of NPM dependencies from JS to TypeScript.  This caused some problem with checks on angular archetype side. This issue is already fixed in the newest version but not released yet. The release of version 24 is planned in a couple of days.

If you want to patch your code in the meanwhile, please follow steps from this PR:
https://github.com/adobe/aem-project-archetype/pull/461

**Comment by msagolj** [comment]
Solution provided in previous comment , thx @blackbyte-pl , closing.
